-- Asset Allocation MCP Server Database Initialization for H2
-- H2-Compatible SQL with IDENTITY syntax (MODE=PostgreSQL)
-- FIXED: Proper order and no DELETE before CREATE

-- Drop tables if they exist (for clean restart)
DROP TABLE IF EXISTS asset_allocations CASCADE;
DROP TABLE IF EXISTS assets CASCADE;
DROP TABLE IF EXISTS asset_categories CASCADE;
DROP TABLE IF EXISTS employees CASCADE;
DROP TABLE IF EXISTS departments CASCADE;

-- Create departments table (H2 IDENTITY)
CREATE TABLE departments (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    manager_name VARCHAR(100),
    budget_allocation DECIMAL(12,2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create employees table (H2 IDENTITY)
CREATE TABLE employees (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id VARCHAR(20) UNIQUE NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    phone VARCHAR(20),
    department_id INT,
    position VARCHAR(100),
    hire_date DATE,
    termination_date DATE,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    manager_id INT,
    location VARCHAR(100),
    cost_center VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create asset_categories table (H2 IDENTITY)
CREATE TABLE asset_categories (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(50) UNIQUE NOT NULL,
    description VARCHAR(255),
    requires_approval BOOLEAN DEFAULT FALSE,
    max_allocation_per_employee INT DEFAULT 1,
    depreciation_years INT DEFAULT 3,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create assets table (H2 IDENTITY)
CREATE TABLE assets (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_tag VARCHAR(50) UNIQUE NOT NULL,
    asset_name VARCHAR(100) NOT NULL,
    category_id INT,
    brand VARCHAR(50),
    model VARCHAR(100),
    serial_number VARCHAR(100) UNIQUE,
    purchase_date DATE,
    purchase_cost DECIMAL(10,2),
    warranty_expiry DATE,
    status VARCHAR(20) DEFAULT 'AVAILABLE',
    condition_status VARCHAR(20) DEFAULT 'NEW',
    location VARCHAR(100),
    vendor VARCHAR(100),
    specifications VARCHAR(2000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create asset_allocations table (H2 IDENTITY) - PLURAL FORM
CREATE TABLE asset_allocations (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id INT,
    employee_id INT,
    allocated_date DATE DEFAULT CURRENT_DATE,
    expected_return_date DATE,
    actual_return_date DATE,
    allocation_status VARCHAR(20) DEFAULT 'ALLOCATED',
    allocation_reason VARCHAR(255),
    approved_by VARCHAR(100),
    approval_date DATE,
    return_condition VARCHAR(20),
    notes VARCHAR(2000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Add foreign key constraints AFTER all tables are created
ALTER TABLE employees ADD CONSTRAINT fk_emp_dept FOREIGN KEY (department_id) REFERENCES departments(id);
ALTER TABLE employees ADD CONSTRAINT fk_emp_mgr FOREIGN KEY (manager_id) REFERENCES employees(id);
ALTER TABLE assets ADD CONSTRAINT fk_asset_category FOREIGN KEY (category_id) REFERENCES asset_categories(id);
ALTER TABLE asset_allocations ADD CONSTRAINT fk_alloc_asset FOREIGN KEY (asset_id) REFERENCES assets(id);
ALTER TABLE asset_allocations ADD CONSTRAINT fk_alloc_emp FOREIGN KEY (employee_id) REFERENCES employees(id);

-- Insert sample departments
INSERT INTO departments (name, description, manager_name, budget_allocation) VALUES
('IT', 'Information Technology', 'John Smith', 500000.00);
INSERT INTO departments (name, description, manager_name, budget_allocation) VALUES
('Engineering', 'Software Engineering', 'Bob Wilson', 750000.00);
INSERT INTO departments (name, description, manager_name, budget_allocation) VALUES
('HR', 'Human Resources', 'Jane Doe', 300000.00);
INSERT INTO departments (name, description, manager_name, budget_allocation) VALUES
('Finance', 'Finance Department', 'Mike Johnson', 450000.00);
INSERT INTO departments (name, description, manager_name, budget_allocation) VALUES
('Marketing', 'Marketing Department', 'Sarah Connor', 350000.00);

-- Insert sample employees  
INSERT INTO employees (employee_id, first_name, last_name, email, phone, department_id, position, hire_date, status, location, cost_center) VALUES
('EMP001', 'John', 'Doe', 'john.doe@company.com', '+1-555-0101', 1, 'Software Engineer', '2023-01-15', 'ACTIVE', 'New York', 'IT001');
INSERT INTO employees (employee_id, first_name, last_name, email, phone, department_id, position, hire_date, status, location, cost_center) VALUES
('EMP002', 'Jane', 'Smith', 'jane.smith@company.com', '+1-555-0102', 1, 'Senior Developer', '2022-08-20', 'ACTIVE', 'New York', 'IT001');
INSERT INTO employees (employee_id, first_name, last_name, email, phone, department_id, position, hire_date, status, location, cost_center) VALUES
('EMP003', 'Bob', 'Wilson', 'bob.wilson@company.com', '+1-555-0103', 2, 'Engineering Manager', '2021-05-10', 'ACTIVE', 'San Francisco', 'ENG001');
INSERT INTO employees (employee_id, first_name, last_name, email, phone, department_id, position, hire_date, status, location, cost_center) VALUES
('EMP004', 'Alice', 'Brown', 'alice.brown@company.com', '+1-555-0104', 3, 'HR Specialist', '2023-03-01', 'ACTIVE', 'Chicago', 'HR001');
INSERT INTO employees (employee_id, first_name, last_name, email, phone, department_id, position, hire_date, status, location, cost_center) VALUES
('EMP005', 'Charlie', 'Davis', 'charlie.davis@company.com', '+1-555-0105', 4, 'Financial Analyst', '2022-11-15', 'ACTIVE', 'Boston', 'FIN001');

-- Insert asset categories
INSERT INTO asset_categories (category_name, description, requires_approval, max_allocation_per_employee, depreciation_years) VALUES
('Laptop', 'Portable computers for employees', TRUE, 1, 3);
INSERT INTO asset_categories (category_name, description, requires_approval, max_allocation_per_employee, depreciation_years) VALUES
('Desktop', 'Desktop computers for workstations', TRUE, 1, 4);
INSERT INTO asset_categories (category_name, description, requires_approval, max_allocation_per_employee, depreciation_years) VALUES
('Monitor', 'External displays', FALSE, 2, 5);
INSERT INTO asset_categories (category_name, description, requires_approval, max_allocation_per_employee, depreciation_years) VALUES
('Phone', 'Mobile phones for communication', TRUE, 1, 2);
INSERT INTO asset_categories (category_name, description, requires_approval, max_allocation_per_employee, depreciation_years) VALUES
('Tablet', 'Tablet devices for mobility', FALSE, 1, 3);
INSERT INTO asset_categories (category_name, description, requires_approval, max_allocation_per_employee, depreciation_years) VALUES
('Headset', 'Audio equipment for calls and meetings', FALSE, 1, 2);
INSERT INTO asset_categories (category_name, description, requires_approval, max_allocation_per_employee, depreciation_years) VALUES
('Keyboard', 'Input devices', FALSE, 1, 3);
INSERT INTO asset_categories (category_name, description, requires_approval, max_allocation_per_employee, depreciation_years) VALUES
('Mouse', 'Pointing devices', FALSE, 1, 2);

-- Insert sample assets
INSERT INTO assets (asset_tag, asset_name, category_id, brand, model, serial_number, purchase_date, purchase_cost, warranty_expiry, status, condition_status, location, vendor, specifications) VALUES
('LAP001', 'Dell Laptop XPS 13', 1, 'Dell', 'XPS 13 9310', 'DL123456789', '2023-01-10', 1299.99, '2026-01-10', 'ALLOCATED', 'GOOD', 'IT Storage', 'Dell Inc', 'Intel i7, 16GB RAM, 512GB SSD');
INSERT INTO assets (asset_tag, asset_name, category_id, brand, model, serial_number, purchase_date, purchase_cost, warranty_expiry, status, condition_status, location, vendor, specifications) VALUES
('LAP002', 'MacBook Pro 14"', 1, 'Apple', 'MacBook Pro M1', 'AP987654321', '2023-02-15', 2399.99, '2026-02-15', 'ALLOCATED', 'EXCELLENT', 'IT Storage', 'Apple Inc', 'M1 Pro, 32GB RAM, 1TB SSD');
INSERT INTO assets (asset_tag, asset_name, category_id, brand, model, serial_number, purchase_date, purchase_cost, warranty_expiry, status, condition_status, location, vendor, specifications) VALUES
('LAP003', 'ThinkPad T14', 1, 'Lenovo', 'ThinkPad T14 Gen 2', 'LN456789123', '2023-03-01', 1099.99, '2026-03-01', 'AVAILABLE', 'NEW', 'IT Storage', 'Lenovo', 'AMD Ryzen 7, 16GB RAM, 256GB SSD');
INSERT INTO assets (asset_tag, asset_name, category_id, brand, model, serial_number, purchase_date, purchase_cost, warranty_expiry, status, condition_status, location, vendor, specifications) VALUES
('DES001', 'Dell OptiPlex 7090', 2, 'Dell', 'OptiPlex 7090', 'DO789123456', '2022-12-01', 899.99, '2025-12-01', 'ALLOCATED', 'GOOD', 'Office Floor 3', 'Dell Inc', 'Intel i5, 8GB RAM, 256GB SSD');
INSERT INTO assets (asset_tag, asset_name, category_id, brand, model, serial_number, purchase_date, purchase_cost, warranty_expiry, status, condition_status, location, vendor, specifications) VALUES
('MON001', 'Dell 27" Monitor', 3, 'Dell', 'S2721DS', 'DM111222333', '2023-01-20', 299.99, '2026-01-20', 'ALLOCATED', 'EXCELLENT', 'Office Floor 3', 'Dell Inc', '27" QHD, USB-C, Height Adjustable');
INSERT INTO assets (asset_tag, asset_name, category_id, brand, model, serial_number, purchase_date, purchase_cost, warranty_expiry, status, condition_status, location, vendor, specifications) VALUES
('MON002', 'LG UltraWide 34"', 3, 'LG', '34WN80C-B', 'LG444555666', '2023-02-10', 449.99, '2026-02-10', 'AVAILABLE', 'NEW', 'IT Storage', 'LG Electronics', '34" WQHD, USB-C, Thunderbolt');
INSERT INTO assets (asset_tag, asset_name, category_id, brand, model, serial_number, purchase_date, purchase_cost, warranty_expiry, status, condition_status, location, vendor, specifications) VALUES
('PHN001', 'iPhone 14 Pro', 4, 'Apple', 'iPhone 14 Pro', 'IP777888999', '2023-01-05', 999.99, '2025-01-05', 'ALLOCATED', 'EXCELLENT', 'Employee Personal', 'Apple Inc', '128GB, 5G, ProRAW Camera');
INSERT INTO assets (asset_tag, asset_name, category_id, brand, model, serial_number, purchase_date, purchase_cost, warranty_expiry, status, condition_status, location, vendor, specifications) VALUES
('TAB001', 'iPad Air 5th Gen', 5, 'Apple', 'iPad Air', 'IA101112131', '2023-02-20', 599.99, '2025-02-20', 'AVAILABLE', 'NEW', 'IT Storage', 'Apple Inc', '64GB, WiFi + Cellular, M1 Chip');

-- Insert sample allocations
INSERT INTO asset_allocations (asset_id, employee_id, allocated_date, allocation_status, allocation_reason, approved_by, approval_date, notes) VALUES
(1, 1, '2023-01-16', 'ALLOCATED', 'New employee onboarding', 'John Smith', '2023-01-15', 'Primary work laptop for software development');
INSERT INTO asset_allocations (asset_id, employee_id, allocated_date, allocation_status, allocation_reason, approved_by, approval_date, notes) VALUES
(2, 2, '2023-02-16', 'ALLOCATED', 'Hardware upgrade', 'John Smith', '2023-02-15', 'Upgraded from previous MacBook Air for performance');
INSERT INTO asset_allocations (asset_id, employee_id, allocated_date, allocation_status, allocation_reason, approved_by, approval_date, notes) VALUES
(4, 3, '2022-12-02', 'ALLOCATED', 'Manager workstation', 'Bob Wilson', '2022-12-01', 'Desktop setup for engineering management tasks');
INSERT INTO asset_allocations (asset_id, employee_id, allocated_date, allocation_status, allocation_reason, approved_by, approval_date, notes) VALUES
(5, 1, '2023-01-21', 'ALLOCATED', 'Dual monitor setup', 'John Smith', '2023-01-20', 'Second monitor for development productivity');
INSERT INTO asset_allocations (asset_id, employee_id, allocated_date, allocation_status, allocation_reason, approved_by, approval_date, notes) VALUES
(7, 4, '2023-01-06', 'ALLOCATED', 'Company phone for HR duties', 'Jane Doe', '2023-01-05', 'Business phone with company plan');

-- Create indexes for performance
CREATE INDEX idx_asset_allocations_employee ON asset_allocations(employee_id);
CREATE INDEX idx_asset_allocations_asset ON asset_allocations(asset_id);
CREATE INDEX idx_assets_status ON assets(status);
CREATE INDEX idx_employees_status ON employees(status);
CREATE INDEX idx_employees_department ON employees(department_id);

-- Completion marker - this will be checked by the Mule initialization flow
INSERT INTO departments (name, description) VALUES ('_INIT_COMPLETE_', 'H2 Asset Allocation DB initialization completed successfully');
